# Theme
minimal_mistakes_skin    : "air"

# Site Settings
locale                   : "en-US"
title                    : "Blanca Martin-Burgos"
title_separator          : "-"
subtitle                 : "Computational Neuroscientist"
name                     : "Blanca Martin-Burgos"
description              : "PhD candidate in Neurosciences at UC San Diego, working on action potential dynamics, neuronal timescales, and circadian rhythms."
url                      : "https://bcmartinb.github.io"
baseurl                  :
repository               : "bcmartinb/bcmartinb.github.io"
teaser                   :
logo                     :
masthead_title           : " "
breadcrumbs              : false
words_per_minute         : 200
copyright                :
copyright_url            :
comments:
  provider               : false
search                   : false

# SEO Related
google_site_verification :
bing_site_verification   :

# Social Sharing
twitter:
  username               :
facebook:
  username               :
og_image                 :
social:
  type                   : Person
  name                   : "Blanca Martin-Burgos"
  links:
    - "https://github.com/bcmartinb"
    - "https://scholar.google.com/citations?user=PNR9T_8AAAAJ"

# Analytics
analytics:
  provider               : false

# Site Author
author:
  name             : "Blanca Martin-Burgos"
  avatar           : "/assets/images/bio-photo.png"
  bio              : "PhD candidate in Neurosciences, UC San Diego"
  location         : "La Jolla, CA"
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:bcmartinb@gmail.com"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bcmartinb"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=PNR9T_8AAAAJ"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/blanca-martin-burgos-b0231a14"

# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/bcmartinb"
    - label: "Google Scholar"
      icon: "fas fa-fw fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=PNR9T_8AAAAJ"

# Reading Files
include:
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Gemfile
  - Gemfile.lock
  - node_modules
  - log
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-include-cache
  - jekyll-sitemap

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-include-cache
  - jekyll-sitemap

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: false
